services:
  line_webhook:
    build:
      context: .
      dockerfile: Dockerfile.webhook
    container_name: pea-line-webhook
    restart: unless-stopped
    env_file:
      - ./.env.webhook
    ports:
      - "5001:5001"
    volumes:
      - ./employees.db:/app/employees.db
