FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.worker.txt /tmp/requirements.worker.txt
RUN pip install --no-cache-dir -r /tmp/requirements.worker.txt

COPY . /app

CMD ["python", "app_ev.py"]
