services:
  ai_worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: pea-ai-worker
    restart: unless-stopped
    env_file:
      - ./.env.worker
    volumes:
      - ./whooutside.db:/app/whooutside.db
